### ISSUE TITLE
Throws buckets of errors when running on system startup

### ISSUE THREAD

**Issue by sig-noi** [raspibolt/raspibolt-pulse#11]
Would there be a way to delay the first run of raspibolt-pulse until after all essential components have started?

**Comment by sig-noi** [comment]
I fooled around with making a systemd raspibolt-pulse.service file that would run After=lnd.service but couldn't figure out how to get it to display in the terminal.. any other ways to make it run in a delayed fashion?

**Comment by ghost** [comment]
This script is meant to be run when the "admin" user logs in (and then anytime we invoke it with `rapsibolt` command). I'm not sure delaying the running of this welcome script would make sense in that context, no?

When I run the script and LND is opening but not up yet, I also see 5-6 yellow error lines that appear at the top of the output.

What about we make the script NOT display these error message and instead we display a message in the Lighnting part of the oupt that states that LND is still launching. Like this the user knows that they have to wait a minute or two and run `raspibolt` again to see LND up. Wdyt of that solution?

**Comment by ghost** [comment]
Regarding the buckets of errors, when do the errors appear..? any specific cases?

**Comment by vicariousdrama** [comment]
Concur. Goal should be to allow the script to run, and quickly, but catch and suppress any errors inline while gathering information, and instead report to the relevant sections.

Any log output you can capture would be helpful in identifying what isn't being handled well, but otherwise we will need to look at each call.

**Comment by ghost** [comment]
```
RaspiBolt 3: Sovereign ₿itcoin full node
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
```
When LND is down, the script output this error message in yellow.

Could we remove these lines from the output? It can causes unnecessary concerns for newbies when they see that.

**Comment by vicariousdrama** [comment]
There are assorted places where stderr output is not being redirected to stdout or /dev/null.
These can be redirected or suppressed as appropriate.
