### ISSUE TITLE
Remove warning when LND is down

### ISSUE THREAD

**Issue by ghost** [raspibolt/raspibolt-pulse#12]
```
RaspiBolt 3: Sovereign ₿itcoin full node
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
```
When LND is down, the script output this error message in yellow.

Could we remove these lines from the output? It can causes unnecessary concerns for newbies when they see that.

**Comment by vicariousdrama** [comment]
Relates to #11

**Comment by ghost** [comment]
> Relates to #11

Good point, Closing this Issue and pasting that error as a comment in #11.
