### ISSUE TITLE
Failed to read CPU temperature

### ISSUE THREAD

**Issue by Buttafuoco** [raspibolt/raspibolt-pulse#18]
I have this errror on loading of script:

**cat: /sys/class/thermal/thermal_zone0/temp: No such file or directory**

![Screenshot at 2022-11-23 22-24-17](https://user-images.githubusercontent.com/52328971/203648609-5fb8248c-f292-4b11-8d43-b10221b174b6.png)

the host is a debian with AMD cpu, this is "sensors" output:

k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +33.4 C  (high = +70.0 C)
                       (crit = +100.0 C, hyst = +99.0 C)

is possible to cat the output of sensors or there is a better way to catch value of temp?

**Comment by vicariousdrama** [comment]
So far the script has been based around the Raspberry Pi.  Different architecture will end up with needing different checks for sensors. It's possible that its using a different thermal_zone* record.  Ideally we wouldnt create more dependencies on additional packages and should be able to read the necessary data from the /sys/class

Can you list the output of
```sh
cat /sys/class/thermal/thermal_zone*/tmp
```

**Comment by Buttafuoco** [comment]
![Screenshot at 2023-01-17 20-37-13](https://user-images.githubusercontent.com/52328971/212995614-241ae280-17d6-44ad-9d9a-d179d72bdf7a.png)
maybe is linked to this:
![Screenshot at 2023-01-17 20-41-37](https://user-images.githubusercontent.com/52328971/212996413-4edad237-6181-4252-bc28-791ec92acf61.png)

**Comment by vicariousdrama** [comment]
ok. That's helpful. No devices listed in the traditional path.

How about if you do this:

```
for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i) = $(cat $i)"; done
```

On my ubuntu system, i get the following

```
acpitz: temp1 /sys/devices/virtual/thermal/thermal_zone0/hwmon0/temp1_input = 27800
acpitz: temp2 /sys/devices/virtual/thermal/thermal_zone0/hwmon0/temp2_input = 29800
coretemp: Package id 0 /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input = 83000
coretemp: Core 0 /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input = 78000
coretemp: Core 1 /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp3_input = 82000
coretemp: Core 2 /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp4_input = 77000
coretemp: Core 3 /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp5_input = 79000
```

I've got some number crunching going on, so my temperatures are high, but still fine for this system

**Comment by vicariousdrama** [comment]
And on raspberry pi units I get this

```
cpu_thermal: temp1 /sys/devices/virtual/thermal/thermal_zone0/hwmon0/temp1_input = 38459
```

Unfortunately with the device and label differences, we'll need to work in some logic to identify the best value to report.

Perhaps we should just find whatever is the highest temperature
```
hitemp=0
for i in /sys/class/hwmon/hwmon*/temp*_input; do readtemp=$(cat $i); if (( readtemp > hitemp )); then hitemp=$readtemp; fi; done
echo $hitemp
```

**Comment by Buttafuoco** [comment]
ok. seem there is only one value for what we need to monitor. i'm impressed about your knowledge about, is from bash scripting experience?
![Screenshot at 2023-01-18 14-18-22](https://user-images.githubusercontent.com/52328971/213181743-1b09b005-822d-4fe0-bc0c-b905238db02b.png)

this is the sensors output in jason, there is not a simpler way to extract value from stdout of this?
![Screenshot at 2023-01-18 14-22-42](https://user-images.githubusercontent.com/52328971/213182982-37dde42a-a5b1-4413-b90e-041b3421d962.png)

**Comment by vicariousdrama** [comment]
It's possible to parse the JSON from that output by piping it to jq but this would create a dependency on installing the sensors package, as well as requiring sudo to run the script.  This is why I'd prefer to keep it to what can be interrogated without sudo

**Comment by Buttafuoco** [comment]
ok, i get it now. 

this is the output you ask
![Screenshot at 2023-01-18 18-08-59](https://user-images.githubusercontent.com/52328971/213258945-ac070fde-f428-4987-91e3-45f844538d79.png)

**Comment by M1ch43lV** [comment]
Hi Vic! 
For the script, can you prevent the failure msg. in case there is no temperature sensor - as for VM Linux systems - and something like N/A is reported on the dashboard for CPU Temp?

**Comment by vicariousdrama** [comment]
Done
