### ISSUE TITLE
Unbound Variable

### ISSUE THREAD

**Issue by ghgeiger** [raspibolt/raspibolt-pulse#9]
I'm trying to replace my legacy System Overview (the old raspibolt startup script) with Raspibolt Pulse & I'm having a problem getting it started. I followed the instructions in this github, did chmod +x after copying it over, and when I run the script I get the following output:
```

RaspiBolt 3: Sovereign ₿itcoin full node
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
/usr/local/bin/raspibolt: line 413: lnd_color: unbound variable
```
I'm not sure what's going on with this. After I ran it for the first time I checked the code & the only thing I saw that I needed to change was `ext_storage2nd="/data"` as I run my OS on an SD card & keep data on SSD & `/data` is where it's mounted. I changed that & it did not resolve the problem. It looks like line 413 has this in it:
`" \`

the lnd_color variable only shows up on line 397

Any Ideas?

**Comment by ghost** [comment]
Do you still see the issue? I can't replictae the error with the latest script.

**Comment by vicariousdrama** [comment]
Before recent updates to raspibolt-pulse, I was seeing this when running with LND as the lnd_color variable is only set in get_LND_data.sh, and until i had the file copied to /usr/local/bin the raspibolt-pulse-switch script would never see it, hence the late error in rendering.

Relatedly, the get_CLN_data script never sets that variable, and instead uses coreln_color.

When updating to newest scripts, the raspibolt-pulse-switch script no longer references lnd_color so this error may be outdated?
